name: Run Azure Login with OpenID Connect
on: [push]

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Run checkout'
      uses: actions/checkout@v2

    - name: "Determiner la variable en fonction de l'email de l'auteur"
      run: |
          az account set --subscription 66233cb2-4e4f-4316-b4e1-d5e9e53a1960
          az aks get-credentials --resource-group exo1_group --name exo1 --overwrite-existing
          if[[$(git log -1 --pretty=format:'%ae') == 'nathan.szigeti@edu.devinci.fr']] then
              kubectl config set-context --current --namespace=workspace-nth-2000
          fi

    - name: 'Run docker build'
      run : docker build -t devouf.azurecr.io/nth-hello-world-app .

    - name: 'Run acr login'
      run: az acr login --name devouf
    
    - name: 'Run docker push'
      run: docker push devouf.azurecr.io/nth-hello-world-app 

    - name: 'Run kubectl apply'
      run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml